### ISSUE TITLE
Repair only works sometime

### ISSUE THREAD

**Issue by puixdk** [ESX-Org/esx_mecanojob#27] opened 2018-08-01 13:32 UTC
For some people the repair work, but other it seems not to work. 
It will be fixed for mechanics but not the car user. This is 50/50, if repair work right now..

**Comment by lilfuchs** [comment] 2018-08-01 14:02
this is a fivem sync issue bug. Have mechanics get in the driver seat first before letting the car owner back in it

**Comment by lilfuchs** [comment] 2018-08-01 14:03
Also duplicate of #24

**Comment by ElPumpo** [comment] 2018-08-05 07:43
Duplicate of #24 open your eyes

**Closed by ElPumpo** 2018-08-05 07:43 UTC
